version: '3'

services:

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smanagement_api_nodejs
    restart: unless-stopped
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PWD=dqm50vnc
      - DATABASE_HOSTNAME=mariadb
      - DATABASE_PORT=3306
      - DATABASE_DB=smanagement
    ports:
      - "3000:3000"   
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules 
    networks: 
      - app-network
    depends_on: 
      - mariadb
    #command: ./wait-for.sh mariadb:3306 -- node index.js

  mariadb:
    build:
      context: ./build/mariadb
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=smanagement
      - MYSQL_ROOT_PASSWORD=dqm50vnc
    ports: 
      - "3306:3306"
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge

volumes:
  node_modules: