version: '3'

services:

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smanagement_api_nodejs
    #restart: unless-stopped
    environment:
      - DATABASE_USERNAME=root
      - DATABASE_PWD=dqm50vnc
      - DATABASE_HOSTNAME=smanagement_api_database
      - DATABASE_PORT=3306
      - DATABASE_DB=smanagement
      - CLOUDANT_URL=https://05cfc43d-1c86-4ae5-bbf9-a9ffb079f4ae-bluemix.cloudantnosqldb.appdomain.cloud
      - CLOUDANT_IAMKEY=iG-1m5wiHQfQz-OAp91bOFCzmiDJ3v2bt9g1MMtWkI6O
      - CLOUDANT_DB_INSTANCE=smanagement-api
    ports:
      - "3000:3000"   
    volumes:
      - .:/home/node/app
      #- node_modules:/home/node/app/node_modules 
    networks: 
      - app-network
    #depends_on: 
    #  - mariadb
    #command: ./wait-for.sh mariadb:3306 -- node index.js

  #mariadb:
  #  build:
  #    context: ./build/mariadb
  #    dockerfile: Dockerfile
  #  command: --default-authentication-plugin=mysql_native_password
  #  container_name: smanagement_api_database
  #  environment:
  #    - MYSQL_DATABASE=smanagement
  #    - MYSQL_ROOT_PASSWORD=dqm50vnc
  #  ports: 
  #    - "3306:3306"
  #  networks: 
  #    - app-network
    
  #rabbitmq:
  #  image: rabbitmq:3.8-alpine
  #  container_name: smanagement_api_mq
  #  ports:
  #    - "5672:5672"

  #memcached:
  #  image: memcached:1.5.19-alpine
  #  container_name: smanagement_api_memcached
  #  ports:
  #    - "11211:11211"


networks: 
  app-network:
    driver: bridge

volumes:
  node_modules: